name = "mm2-script-decoder"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-01-01"

[env.production]
name = "mm2-script-decoder"
workers_dev = true

[[kv_namespaces]]
binding = "SCRIPTS"
id = ""
preview_id = ""
